export const config = {
  component: "happy-birthay/mickey-mouse-1/Production",
  width: 360,
  height: 640,
  durationInFrames: 960,
  with_watermark: false,  
  fps: 30,
  first_message: "¡TE INVITO",
  second_message: "A MI FIESTA!",  
  third_message: "Happy Checho",  
  fourth_message: "Cumple",
  fifth_message: "5",
  sixth_message: "Añitos",
  seventh_message: "Fecha",
  eighth_message: "23 de Septiembre",
  nineth_message: "Hora",
  tenth_message: "5:00 PM",
  eleventh_message: "Lugar",
  twelfth_message: "Av. Alejandro Santiago #363",
  thirteenth_message: "Te Esperamos",
  fourteenth_message: "¡No Faltes!",
};
