export const config = {
  component: "happy-birthay/mickey-mouse-1/Production",
  width: 360,
  height: 640,
  durationInFrames: 960,
  with_watermark: false,  
  fps: 30,
  first_message: "Te Invito!",
  second_message: "A mi Fiesta",  
  third_message: "Happy Checho",  
  fourth_message: "Cumple",
  fifth_message: "5",
  sixth_message: "Añitos",
  seventh_message: "Acompáñanos a Celebrar Este Gran Día",
  eighth_message: "Fecha",
  nineth_message: "23 de Septiembre",
  tenth_message: "Hora",
  eleventh_message: "5:00 PM",
  twelfth_message: "Lugar",
  thirteenth_message: "Av. Alejandro Santiago #363",
  fourteenth_message: "(Parque de las Palmeras)",
  fifteenth_message: "Te Esperamos!",
  sixteenth_message: "No Faltes!",
};
